/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValuationRouteImport } from './routes/valuation'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as OfferToPurchaseRouteImport } from './routes/offer-to-purchase'
import { Route as NeighborhoodsRouteImport } from './routes/neighborhoods'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BondCalculatorRouteImport } from './routes/bond-calculator'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ValuationRoute = ValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferToPurchaseRoute = OfferToPurchaseRouteImport.update({
  id: '/offer-to-purchase',
  path: '/offer-to-purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsRoute = NeighborhoodsRouteImport.update({
  id: '/neighborhoods',
  path: '/neighborhoods',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BondCalculatorRoute = BondCalculatorRouteImport.update({
  id: '/bond-calculator',
  path: '/bond-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRoute
  '/bond-calculator': typeof BondCalculatorRoute
  '/careers': typeof CareersRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/neighborhoods': typeof NeighborhoodsRoute
  '/offer-to-purchase': typeof OfferToPurchaseRoute
  '/properties': typeof PropertiesRoute
  '/services': typeof ServicesRoute
  '/valuation': typeof ValuationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRoute
  '/bond-calculator': typeof BondCalculatorRoute
  '/careers': typeof CareersRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/neighborhoods': typeof NeighborhoodsRoute
  '/offer-to-purchase': typeof OfferToPurchaseRoute
  '/properties': typeof PropertiesRoute
  '/services': typeof ServicesRoute
  '/valuation': typeof ValuationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/blog': typeof BlogRoute
  '/bond-calculator': typeof BondCalculatorRoute
  '/careers': typeof CareersRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/neighborhoods': typeof NeighborhoodsRoute
  '/offer-to-purchase': typeof OfferToPurchaseRoute
  '/properties': typeof PropertiesRoute
  '/services': typeof ServicesRoute
  '/valuation': typeof ValuationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/blog'
    | '/bond-calculator'
    | '/careers'
    | '/compliance'
    | '/contact'
    | '/dashboard'
    | '/legal'
    | '/login'
    | '/neighborhoods'
    | '/offer-to-purchase'
    | '/properties'
    | '/services'
    | '/valuation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/blog'
    | '/bond-calculator'
    | '/careers'
    | '/compliance'
    | '/contact'
    | '/dashboard'
    | '/legal'
    | '/login'
    | '/neighborhoods'
    | '/offer-to-purchase'
    | '/properties'
    | '/services'
    | '/valuation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/blog'
    | '/bond-calculator'
    | '/careers'
    | '/compliance'
    | '/contact'
    | '/dashboard'
    | '/legal'
    | '/login'
    | '/neighborhoods'
    | '/offer-to-purchase'
    | '/properties'
    | '/services'
    | '/valuation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  BlogRoute: typeof BlogRoute
  BondCalculatorRoute: typeof BondCalculatorRoute
  CareersRoute: typeof CareersRoute
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  NeighborhoodsRoute: typeof NeighborhoodsRoute
  OfferToPurchaseRoute: typeof OfferToPurchaseRoute
  PropertiesRoute: typeof PropertiesRoute
  ServicesRoute: typeof ServicesRoute
  ValuationRoute: typeof ValuationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valuation': {
      id: '/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof ValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer-to-purchase': {
      id: '/offer-to-purchase'
      path: '/offer-to-purchase'
      fullPath: '/offer-to-purchase'
      preLoaderRoute: typeof OfferToPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods': {
      id: '/neighborhoods'
      path: '/neighborhoods'
      fullPath: '/neighborhoods'
      preLoaderRoute: typeof NeighborhoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bond-calculator': {
      id: '/bond-calculator'
      path: '/bond-calculator'
      fullPath: '/bond-calculator'
      preLoaderRoute: typeof BondCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  BlogRoute: BlogRoute,
  BondCalculatorRoute: BondCalculatorRoute,
  CareersRoute: CareersRoute,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  NeighborhoodsRoute: NeighborhoodsRoute,
  OfferToPurchaseRoute: OfferToPurchaseRoute,
  PropertiesRoute: PropertiesRoute,
  ServicesRoute: ServicesRoute,
  ValuationRoute: ValuationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
